[package]
name = "scv-provider-openai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "OpenAI-compatible streaming provider for Peon"
readme = "../../README.md"

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
scv-core.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
